version: '3.7'

networks:
  default:
    name: weaver

services:
  registry:
    hostname: registry
    build:
      dockerfile: Dockerfile
      context: './'
    environment:
      - COMMAND=start:registry
    ports:
      - 4873:4873

  publish:
    build:
      dockerfile: Dockerfile
      context: './'
    environment:
      - COMMAND=publish:registry
    depends_on:
      - registry
