version: '3.7'

networks:
  default:
    name: weaver

services:
  registry:
    image: registry
    hostname: registry
    build:
      dockerfile: Dockerfile
      context: './'
    environment:
      - COMMAND=start:registry
    volumes:
      - ./.verdaccio/storage:/weaver/source/.verdaccio/storage
    ports:
      - 4873:4873

  publish:
    image: registry
    build:
      dockerfile: Dockerfile
      context: './'
    environment:
      - COMMAND=publish:registry
    depends_on:
      - registry
